session:
    maxAge: "1h"
    domain: "localhost"
    name: "session"
    sessionSecret: "K3bo@rdC4t"
    secure: false
    resave: true
    rolling: true
    unset: "destroy"
    secretAlgo: "sha512"

engine:
    host: "localhost"
    port: 3000
    enableETag: true
    maximumRequestBodySize: "100kb"
    useQueryStringLibrary: true

csp:
    enable: true
    includeSelf: true
    length: 32
    nonceAlgo: "sha512"
    hashes: []

csrf:
    enable: true

cors:
    enable: true
    policy: "same-origin"
    allowForeignCredentials: false
    allowedMethods:
        - "GET"
        - "HEAD"
        - "PUT"
        - "PATCH"
        - "POST"
        - "DELETE"
    allowedHeaders:
        - "content-type"
        - "redirect"
        - "mode"
    allowedOrigins:
        - "capacitor://localhost"
        - "ionic://localhost"
        - "http://localhost"
        - "http://localhost:8080"
        - "http://localhost:8100"
