test:
    aString: LOL
    aNumber: 42
    aListOfNumbers:
        - 11
        - 22
        - 33
    aListOfStrings:
        - "11"
        - "22"
        - "33"
    aMixedList:
        - 1
        - "2"
        - true
        - "4"
        - 5
        - false
    aDeepObject:
        layer1:
            layer2:
                layer3:
                    prop31: "test"
                    prop32: 44
                prop21: "testen"
                prop22: 45
            prop11: "meep"
            prop12: 77
        layerOther: "hihi"
testen: "meep"
testatstisch:
    deep:
        - true
        - false
